# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'required': 'Please enter blog title'}, max_length=200)),
                ('content', models.TextField(error_messages={'required': 'Please enter your informatiion'})),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('slug', models.SlugField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('discard', 'Discard'), ('draft', 'Draft'), ('publish', 'Publish'), ('archive', 'Archive')], max_length=10)),
                ('rating', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(error_messages={'required': 'Please enter your first name'}, max_length=100)),
                ('last_name', models.CharField(error_messages={'required': 'Please enter your last name'}, max_length=100)),
                ('email', models.EmailField(error_messages={'required': 'Please enter valid email address'}, help_text='Email', max_length=100)),
                ('password', models.CharField(error_messages={'required': 'Please enter password'}, max_length=100)),
                ('contact_no', models.IntegerField(error_messages={'required': 'Please enter your contact number'}, max_length=20)),
                ('address', models.TextField(error_messages={'required': 'Please enter your address'})),
                ('about_me', models.TextField(error_messages={'required': 'Please enter your informatiion'})),
                ('activation_token', models.CharField(max_length=100)),
                ('socialmedia_key', models.CharField(max_length=200)),
                ('user_photo', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='postid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.User'),
        ),
    ]
