# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_auto_20160226_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(max_length=10),
        ),
    ]
