# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_auto_20160301_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_no',
            field=models.IntegerField(),
        ),
    ]
