# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0006_auto_20160302_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
