# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0007_auto_20160302_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='socialmedia_key',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_photo',
            field=models.CharField(max_length=200),
        ),
    ]
