# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0008_auto_20160302_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
