# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0009_auto_20160303_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
