# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0010_auto_20160308_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_photo',
            field=models.ImageField(upload_to='/media/blog'),
        ),
    ]
